// packages/webpack-plugin/lib/runtime/components/react/mpx-web-view.tsx
import { forwardRef, JSX, useEffect } from 'react'
// @ts-ignore
import { noop } from '@mpxjs/utils'
import { Portal } from '@ant-design/react-native'
import { getCustomEvent } from './getInnerListeners'
import { promisify, redirectTo, navigateTo, navigateBack, reLaunch, switchTab } from '@mpxjs/api-proxy'
// @ts-ignore
import { WebView } from 'react-native-webview'
import useNodesRef, { HandlerRef } from './useNodesRef'

type OnMessageCallbackEvent = {
  detail: {
    data: any[]
  }
}

type CommonCallbackEvent = {
  detail: {
    src?: string
  }
}

interface WebViewProps {
  src: string
  bindmessage?: (event: OnMessageCallbackEvent) => void
  bindload?: (event: CommonCallbackEvent) => void
  binderror?: (event: CommonCallbackEvent) => void
}

interface PayloadData {
  data?: Record<string, any>
}

type MessageData = {
  payload?: PayloadData,
  type?: string,
  callbackId?: number
}

interface NativeEvent {
  url: string,
  data: string
}

interface LoadRes {
  timeStamp: string,
  nativeEvent: NativeEvent
}

interface FormRef {
  postMessage: (value: any) => void;
}

const _WebView = forwardRef<HandlerRef<WebView, WebViewProps>, WebViewProps>((props, ref): JSX.Element => {
  const { src, bindmessage = noop, bindload = noop, binderror = noop } = props

  const defaultWebViewStyle = {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0
  }

  const { nodeRef: webViewRef } = useNodesRef<WebView, WebViewProps>(props, ref, {
    defaultStyle: defaultWebViewStyle
  })

  const _messageList: any[] = []
  const handleUnload = () => {
    // 这里是 WebView 销毁前执行的逻辑
    bindmessage(getCustomEvent('messsage', {}, {
      detail: {
        data: _messageList
      },
      layoutRef: webViewRef
    }))
  }

  useEffect(() => {
    // 组件卸载时执行
    return () => {
      handleUnload()
    }
  }, [])
  const _load = function (res: LoadRes) {
    const result = {
      type: 'load',
      timeStamp: res.timeStamp,
      detail: {
        src: res.nativeEvent?.url
      }
    }
    bindload(result)
  }
  const _error = function (res: LoadRes) {
    const result = {
      type: 'error',
      timeStamp: res.timeStamp,
      detail: {
        src: ''
      }
    }
    binderror(result)
  }
  const _message = function (res: LoadRes) {
    let data: MessageData
    let asyncCallback
    const navObj = promisify({ redirectTo, navigateTo, navigateBack, reLaunch, switchTab })
    try {
      const nativeEventData = res.nativeEvent?.data
      data = JSON.parse(nativeEventData)
    } catch (e) {
      data = {}
    }
    const postData: PayloadData = data.payload || {}
    switch (data.type) {
      case 'postMessage':
        _messageList.push(postData.data)
        asyncCallback = Promise.resolve({
          errMsg: 'invokeWebappApi:ok'
        })
        break
      case 'navigateTo':
        asyncCallback = navObj.navigateTo(postData)
        break
      case 'navigateBack':
        asyncCallback = navObj.navigateBack(postData)
        break
      case 'redirectTo':
        asyncCallback = navObj.redirectTo(postData)
        break
      case 'switchTab':
        asyncCallback = navObj.switchTab(postData)
        break
      case 'reLaunch':
        asyncCallback = navObj.reLaunch(postData)
        break
    }

    asyncCallback && asyncCallback.then((res: any) => {
      if (webViewRef.current?.postMessage) {
        const test = JSON.stringify({
          type: data.type,
          callbackId: data.callbackId,
          result: res
        })
        webViewRef.current.postMessage(test)
      }
    })
  }
  return (<Portal>
    <WebView
      style={defaultWebViewStyle}
      source={{ uri: src }}
      ref={webViewRef}
      onLoad={_load}
      onError={_error}
      onMessage={_message}
      javaScriptEnabled={true}
    ></WebView>
  </Portal>)
})

_WebView.displayName = 'mpx-web-view'

export default _WebView

// packages/webpack-plugin/lib/runtime/components/web/mpx-web-view.vue
<template>
  <iframe ref="mpxIframe" class="mpx-iframe" :src="currentUrl" :key="currentUrl"></iframe>
</template>

<script>
import { getCustomEvent } from './getInnerListeners'
import { promisify, redirectTo, navigateTo, navigateBack, reLaunch, switchTab } from '@mpxjs/api-proxy'
import { extend, isFunction } from '@mpxjs/utils'

const navObj = promisify({ redirectTo, navigateTo, navigateBack, reLaunch, switchTab })
const eventLoad = 'load'
const eventError = 'error'
const eventMessage = 'message'
const mpx = global.__mpx
export default {
  props: {
    src: {
      type: String
    }
  },
  computed: {
    host () {
      let host = this.src.split('/')
      if (host[2]) {
        host = host[0] + '//' + host[2]
      } else {
        host = ''
      }
      return host
    },
    currentUrl () {
      if (!this.src) return ''
      const hostValidate = this.hostValidate(this.host)
      if (!hostValidate) {
        console.error('访问页面域名不符合domainWhiteLists白名单配置，请确认是否正确配置该域名白名单')
        return ''
      }
      let src
      const srcQueryIndex = this.src.indexOf('?')
      // webview与被打开页面通过_uid确定关联关系
      if (srcQueryIndex > -1) {
        src = `${this.src.substring(0, srcQueryIndex + 1)}mpx_webview_id=${this._uid}&${this.src.substring(srcQueryIndex + 1)}`
      } else {
        src = `${this.src}?mpx_webview_id=${this._uid}`
      }
      return src
    },
    loadData () {
      return {
        src: this.host,
        fullUrl: this.src
      }
    }
  },
  watch: {
    currentUrl: {
      handler (value) {
        if (!value) {
          this.$emit(eventError, getCustomEvent(eventError, extend({
            errMsg: 'web-view load failed due to not in domain list'
          }, this.loadData), this))
        } else {
          this.$nextTick(() => {
            if (this.$refs.mpxIframe && this.mpxIframe != this.$refs.mpxIframe) {
              this.mpxIframe = this.$refs.mpxIframe
              this.mpxIframe.addEventListener('load', () => {
                this.$emit(eventLoad, getCustomEvent(eventLoad, this.loadData, this))
              })
            }
          })
        }
      },
      immediate: true
    }
  },
  beforeCreate () {
    this.messageList = []
  },
  mounted () {
    window.addEventListener('message', this.messageCallback)
  },
  deactivated () {
    if (!this.messageList.length) {
      return
    }
    let data = {
      type: 'message',
      data: this.messageList
    }
    this.$emit(eventMessage, getCustomEvent(eventMessage, data, this))
  },
  destroyed () {
    window.removeEventListener('message', this.messageCallback)
    if (!this.messageList.length) {
      return
    }
    let data = {
      type: 'message',
      data: this.messageList
    }
    this.$emit(eventMessage, getCustomEvent(eventMessage, data, this))
  },
  methods: {
    messageCallback (event) {
      const hostValidate = this.hostValidate(event.origin)
      let data = {}
      try {
        const eventData = event.data
        data = typeof eventData === 'string' ? JSON.parse(eventData) : eventData
      } catch(e){}
      // 判断number类型，防止undefined导致触发return逻辑
      if (data.clientUid !== undefined && +data.clientUid !== this._uid) {
        return
      }
      let value = data.payload
      const args = data.args
      const params = Array.isArray(args) ? args : [value]
      if (!hostValidate) {
        return
      }
      let asyncCallback = null
      const type = data.type
      switch (type) {
        case 'postMessage':
          let data = {
            type: 'message',
            data: params[0]?.data || params[0] // 补充兜底逻辑
          }
          this.$emit(eventMessage, getCustomEvent(eventMessage, data, this))
          asyncCallback = Promise.resolve({
            errMsg: 'invokeWebappApi:ok'
          })
          break
        case 'navigateTo':
          asyncCallback = navObj.navigateTo(...params)
          break
        case 'navigateBack':
          asyncCallback = navObj.navigateBack(...params)
          break
        case 'redirectTo':
          asyncCallback = navObj.redirectTo(...params)
          break
        case 'switchTab':
          asyncCallback = navObj.switchTab(...params)
          break
        case 'reLaunch':
          asyncCallback = navObj.reLaunch(...params)
          break
        default:
          if (type) {
            const implement = mpx.config.webConfig?.webviewConfig?.apiImplementations?.[type]
            if (isFunction(implement)) {
              asyncCallback = Promise.resolve(implement(...params))
            } else {
              asyncCallback = Promise.reject({
                errMsg: `未在apiImplementations中配置${type}方法`
              })
            }
          }
          break
      }
      asyncCallback && asyncCallback.then((res) => {
        this.mpxIframe && this.mpxIframe.contentWindow && this.mpxIframe.contentWindow.postMessage && this.mpxIframe.contentWindow.postMessage({
          type: type,
          callbackId: data.callbackId,
          result: res
        }, event.origin)
      }).catch((error) => {
        this.mpxIframe && this.mpxIframe.contentWindow && this.mpxIframe.contentWindow.postMessage && this.mpxIframe.contentWindow.postMessage({
          type: type,
          callbackId: data.callbackId,
          error
        }, event.origin)
      })
    },
    hostValidate (host) {
      const hostWhitelists = mpx.config.webConfig?.webviewConfig?.hostWhitelists || []
      if (hostWhitelists.length) {
        return hostWhitelists.some((item) => {
          return host.endsWith(item)
        })
      } else {
        return true
      }
    }
  }
}
</script>

<style>
.mpx-iframe {
  width: 100%;
  height: 100%;
  position: absolute;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
}
</style>
